package com.becoda.bkms.east.tjbb.dao;


import java.util.List;

import com.becoda.bkms.common.dao.GenericDAO;
import com.becoda.bkms.pcs.util.DateUtil;
import com.becoda.bkms.sys.pojo.bo.CodeItemBO;
import com.farm.core.sql.query.DataQuery;
/**
 * 统计报表
 */
public class TjbbDAO extends GenericDAO{
	
	public DataQuery yddlfpd(DataQuery query){
		/*DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('2017-12' as varchar(10)) as rq,a.ynsb_glbh,a.ynsb_nyzl,b.ynsbsis_mc," + 
				" b.ynsbsis_bs,c.sistime as last1time,d.sistime as last2time,c.sisvalue as last1value," + 
				" d.sisvalue as last2value,c.sisvalue - d.sisvalue as ljz,(c.sisvalue - d.sisvalue) * 0.05 as shl,(c.sisvalue - d.sisvalue) * 1.05 as byjsl " + 
				
				" FROM EAST_YNSB a left join EAST_YNSBSIS b on b.ynsb_id = a.ynsb_id" + 
				" left join (select * from zd_test2 where (sistime,sisid) in " + 
				" (select max(sistime),sisid from zd_test2 where sistime like '2017-12%' group by sisid)) c " + 
				" on c.sisid = b.ynsbsis_bs" + 
				" left join (select * from zd_test2 where (sistime,sisid) in " + 
				" (select max(sistime),sisid from zd_test2 where sistime like '2017-11%' group by sisid)) d" + 
				" on d.sisid = b.ynsbsis_bs" + 
				
				" where b.ynsbsis_islj = '1'" + 
				" and a.ynsb_fid = '3010401101')",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");*/
		
		DataQuery dbQuery = DataQuery
		.init(query,
				"EAST_TJBB_YDDLFPD",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,SJJSL,JFZT,(CASE  WHEN JFZT='0' THEN '未缴费' WHEN JFZT='1' THEN '已缴费' END) AS JFZTNAME,BJ  ");
		return dbQuery;
	}
	
	public DataQuery yddlfpd1(DataQuery query, String rq){
		String lastLastYearMonth = DateUtil.getLastDayOfLastMonth(rq);
		String lastYearMonth = DateUtil.getLastDayOfMonth(rq);
		DataQuery dbQuery = DataQuery
		.init(query,
				" ( SELECT sys_guid() as id,cast('"+rq+"' as varchar(10)) AS rq, '1#锅炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c00a000e8' and sis.ynsbsis_bs = '75tyc_1FGASLOOPPV_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c00a000e8' and sis.ynsbsis_bs = '75tyc_1FGASLOOPPV_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m  " +
				             " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#锅炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c2f1100e9' and sis.ynsbsis_bs = '75tyc_2FGASLOOPPV_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c2f1100e9' and sis.ynsbsis_bs = '75tyc_2FGASLOOPPV_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1#锅炉蒸汽流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d1a0b00ee' and sis.ynsbsis_bs = '75tyc_F101_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d1a0b00ee' and sis.ynsbsis_bs = '75tyc_F101_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#锅炉蒸汽流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d647600ef' and sis.ynsbsis_bs = '75tyc_F201_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d647600ef' and sis.ynsbsis_bs = '75tyc_F201_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1#锅炉水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' as varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2cb90e00ec' and sis.ynsbsis_bs = '75tyc_F103_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2cb90e00ec' and sis.ynsbsis_bs = '75tyc_F103_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#锅炉水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' as varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2ceb2700ed' and sis.ynsbsis_bs = '75tyc_F203_CT' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2ceb2700ed' and sis.ynsbsis_bs = '75tyc_F203_CT' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 ")",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");
		return dbQuery;
	}
	
	public DataQuery yddlfpd2(DataQuery query, String rq){
		String lastLastYearMonth = DateUtil.getLastDayOfLastMonth(rq);
		String lastYearMonth = DateUtil.getLastDayOfMonth(rq);
		DataQuery dbQuery = DataQuery
		.init(query,
				" ( SELECT sys_guid() as id,cast('"+rq+"' as varchar(10)) AS rq, '换热机组一次进口蒸汽表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '2' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2eeedc00f1' and sis.ynsbsis_bs = 'rhzYC_1809' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2eeedc00f1' and sis.ynsbsis_bs = 'rhzYC_1809' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m  " +
				             " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '换热机组一次出口热量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '8' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2e007300f0' and sis.ynsbsis_bs = 'rhzYC_1769' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2e007300f0' and sis.ynsbsis_bs = 'rhzYC_1769' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '换热机组补水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2f36d600f2' and sis.ynsbsis_bs = 'rhzYC_1766' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2f36d600f2' and sis.ynsbsis_bs = 'rhzYC_1766' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 ")",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");
		return dbQuery;
	}
	
	public DataQuery yddlfpd3(DataQuery query, String rq){
		String lastLastYearMonth = DateUtil.getLastDayOfLastMonth(rq);
		String lastYearMonth = DateUtil.getLastDayOfMonth(rq);
		DataQuery dbQuery = DataQuery
		.init(query,
				" ( SELECT sys_guid() as id,cast('"+rq+"' as varchar(10)) AS rq, '动力南厂燃机1' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f2fe40700f3' and sis.ynsbsis_bs = 'NC_NFQ3' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f2fe40700f3' and sis.ynsbsis_bs = 'NC_NFQ3' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m  " +
				             " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '动力南厂燃机2' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3023db00f4' and sis.ynsbsis_bs = 'NC_NFQ4' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3023db00f4' and sis.ynsbsis_bs = 'NC_NFQ4' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '工业用蒸汽（一抽）' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f311b7100f8' and sis.ynsbsis_bs = 'NC_21' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f311b7100f8' and sis.ynsbsis_bs = 'NC_21' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '供暖用蒸汽（二抽）' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3156cd00f9' and sis.ynsbsis_bs = 'NC_22' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3156cd00f9' and sis.ynsbsis_bs = 'NC_22' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1#机发电' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '7' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3054f900f5' and sis.ynsbsis_bs = 'nc_10cfa10ce001energy' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3054f900f5' and sis.ynsbsis_bs = 'nc_10cfa10ce001energy' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#机发电' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '7' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30805e00f6' and sis.ynsbsis_bs = 'nc_20cfa10ce001energy' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30805e00f6' and sis.ynsbsis_bs = 'nc_20cfa10ce001energy' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '3#机发电' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '7' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30ae4300f7' and sis.ynsbsis_bs = 'nc_00cfa10ce001energy' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30ae4300f7' and sis.ynsbsis_bs = 'nc_00cfa10ce001energy' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1#余热炉给水（低压）' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f34b40d0106' and sis.ynsbsis_bs = 'NC_18' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f34b40d0106' and sis.ynsbsis_bs = 'NC_18' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#余热炉给水（低压）' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '40288035607c521801607cddef450000' and sis.ynsbsis_bs = 'NC_20' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '40288035607c521801607cddef450000' and sis.ynsbsis_bs = 'NC_20' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 ")",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");
		return dbQuery;
	}
	public DataQuery yddlfpd4(DataQuery query, String rq){
		String lastLastYearMonth = DateUtil.getLastDayOfLastMonth(rq);
		String lastYearMonth = DateUtil.getLastDayOfMonth(rq);
		DataQuery dbQuery = DataQuery
		.init(query,
				" ( SELECT sys_guid() as id,cast('"+rq+"' as varchar(10)) AS rq, '1#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f370ce00109' and sis.ynsbsis_bs = 'NC_1' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f370ce00109' and sis.ynsbsis_bs = 'NC_1' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m  " +
				             " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f373dff010a' and sis.ynsbsis_bs = 'NC_2' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f373dff010a' and sis.ynsbsis_bs = 'NC_2' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '3#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37741e010b' and sis.ynsbsis_bs = 'NC_3' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37741e010b' and sis.ynsbsis_bs = 'NC_3' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '4#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f379fb2010c' and sis.ynsbsis_bs = 'NC_4' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f379fb2010c' and sis.ynsbsis_bs = 'NC_4' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '供暖用蒸汽' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '2' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3c24890116' and sis.ynsbsis_bs = 'NC_22' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3c24890116' and sis.ynsbsis_bs = 'NC_22' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '动力南厂热水出口表2' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '9' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3d31930118' and sis.ynsbsis_bs = 'NC_16' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3d31930118' and sis.ynsbsis_bs = 'NC_16' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1期换热机组补水' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b66172fb530161731ba7370008' and sis.ynsbsis_bs = 'NC_F1_LJ' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b66172fb530161731ba7370008' and sis.ynsbsis_bs = 'NC_F1_LJ' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2期换热机组补水' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f397dd00111' and sis.ynsbsis_bs = 'NC_13' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f397dd00111' and sis.ynsbsis_bs = 'NC_13' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '1#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37d52e010d' and sis.ynsbsis_bs = 'NC_6' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37d52e010d' and sis.ynsbsis_bs = 'NC_6' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '2#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37f83a010e' and sis.ynsbsis_bs = 'NC_8' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37f83a010e' and sis.ynsbsis_bs = 'NC_8' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '3#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f381a9a010f' and sis.ynsbsis_bs = 'NC_10' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f381a9a010f' and sis.ynsbsis_bs = 'NC_10' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '4#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3840160110' and sis.ynsbsis_bs = 'NC_12' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3840160110' and sis.ynsbsis_bs = 'NC_12' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 
							 ")",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");
		return dbQuery;
	}
	public DataQuery yddlfpd5(DataQuery query, String rq){
		String lastLastYearMonth = DateUtil.getLastDayOfLastMonth(rq);
		String lastYearMonth = DateUtil.getLastDayOfMonth(rq);
		DataQuery dbQuery = DataQuery
		.init(query,
				" ( SELECT sys_guid() as id,cast('"+rq+"' as varchar(10)) AS rq, '蒸汽炉1#燃气' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4011840119' and sis.ynsbsis_bs = 'NC_18' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4011840119' and sis.ynsbsis_bs = 'NC_18' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m  " +
				             " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '蒸汽炉2#燃气' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4451fd011a' and sis.ynsbsis_bs = 'NC_F104_LJ' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4451fd011a' and sis.ynsbsis_bs = 'NC_F104_LJ' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '蒸汽炉蒸汽表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '2' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4785f6011f' and sis.ynsbsis_bs = 'NC_F101_LJ' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4785f6011f' and sis.ynsbsis_bs = 'NC_F101_LJ' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 " union all SELECT sys_guid() as id,'"+rq+"' AS rq, '蒸汽炉给水' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, to_char(m.after - m.before) * 0.05 AS SHL, to_char(m.after - m.before) * 1.05 AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid from ( SELECT '1' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastLastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f46548b011e' and sis.ynsbsis_bs = 'NC_F102_LJ' union all SELECT '2' as rid, c.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id left join (select * FROM zd_test2 WHERE (sistime, sisid) in (select max(sistime), sisid FROM zd_test2 WHERE sistime like '"+lastYearMonth+"%' group by sisid)) c on c.sisid = sis.ynsbsis_bs WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f46548b011e' and sis.ynsbsis_bs = 'NC_F102_LJ' ) t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
							 ")",
				"ID,RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT RQ, YNSB_GLBH, LAST1VALUE, LAST2VALUE, YNSB_NYZL, LJZ, SHL, BYJSL, ynsb_fid FROM EAST_TJBB_NYYHSJRBB WHERE 1 = 1 AND RQ = '"+rq+"' )",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb1(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('"+rq+"' as varchar(10)) AS rq, cast('1#锅炉燃气表' as varchar(20))  AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c00a000e8' and sis.ynsbsis_bs = '75tyc_1FGASLOOPPV_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '2#锅炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2c2f1100e9' and sis.ynsbsis_bs = '75tyc_2FGASLOOPPV_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '1#锅炉水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2cb90e00ec' and sis.ynsbsis_bs = '75tyc_F103_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '2#锅炉水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2ceb2700ed' and sis.ynsbsis_bs = '75tyc_F203_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '1#锅炉蒸汽流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d1a0b00ee' and sis.ynsbsis_bs = '75tyc_F101_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '2#锅炉蒸汽流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '3' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401104' and sb.ynsb_id = '402894b85f0e303a015f0f2d647600ef' and sis.ynsbsis_bs = '75tyc_F201_CT') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						")",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb2(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('"+rq+"' as varchar(10)) AS rq, cast('换热机组一次进口蒸汽表' as varchar(20))  AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '2' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2eeedc00f1' and sis.ynsbsis_bs = 'rhzYC_1809') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '换热机组一次出口热量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '8' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2e007300f0' and sis.ynsbsis_bs = 'rhzYC_1769') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '换热机组补水流量表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '10' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401105' and sb.ynsb_id = '402894b85f0e303a015f0f2f36d600f2' and sis.ynsbsis_bs = 'rhzYC_1766') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						")",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb3(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('1#余热炉给水（低压）' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f34b40d0106' and sis.ynsbsis_bs = 'NC_18') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('2#余热炉给水（低压）' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '40288035607c521801607cddef450000' and sis.ynsbsis_bs = 'NC_20') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('动力南厂燃机1' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f2fe40700f3' and sis.ynsbsis_bs = 'NC_NFQ3') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('动力南厂燃机2' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3023db00f4' and sis.ynsbsis_bs = 'NC_NFQ4') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('1#机发电' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('7' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3054f900f5' and sis.ynsbsis_bs = 'nc_10cfa10ce001energy') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('2#机发电' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('7' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30805e00f6' and sis.ynsbsis_bs = 'nc_20cfa10ce001energy') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('3#机发电' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('7' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f30ae4300f7' and sis.ynsbsis_bs = 'nc_00cfa10ce001energy') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('工业用蒸汽（一抽）' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('3' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f311b7100f8' and sis.ynsbsis_bs = 'NC_21') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('供暖用蒸汽（二抽）' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('3' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401107' and sb.ynsb_id = '402894b85f0e303a015f0f3156cd00f9' and sis.ynsbsis_bs = 'NC_22') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				")",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb4(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('"+rq+"' as varchar(10)) AS rq, '动力南厂热水出口表2' AS YNSB_GLBH, m.after  AS LAST1VALUE, m.before AS LAST2VALUE, cast('9' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3d31930118' and sis.ynsbsis_bs = 'NC_16') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
						" union all SELECT '"+rq+"' AS rq, '1#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f370ce00109' and sis.ynsbsis_bs = 'NC_1') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
						" union all SELECT '"+rq+"' AS rq, '2#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, '1' AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f373dff010a' and sis.ynsbsis_bs = 'NC_2') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
						" union all SELECT '"+rq+"' AS rq, '3#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37741e010b' and sis.ynsbsis_bs = 'NC_3') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
						" union all SELECT '"+rq+"' AS rq, '4#热水炉燃气表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f379fb2010c' and sis.ynsbsis_bs = 'NC_4') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '供暖用蒸汽' AS YNSB_GLBH, m.after  AS LAST1VALUE, m.before AS LAST2VALUE, cast('2' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3c24890116' and sis.ynsbsis_bs = 'NC_22') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
						" union all SELECT '"+rq+"' AS rq, '1期换热机组补水' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b66172fb530161731ba7370008' and sis.ynsbsis_bs = 'NC_F1_LJ') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '2期换热机组补水' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f397dd00111' and sis.ynsbsis_bs = 'NC_13') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '1#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37d52e010d' and sis.ynsbsis_bs = 'NC_6') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '2#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f37f83a010e' and sis.ynsbsis_bs = 'NC_8') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '3#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f381a9a010f' and sis.ynsbsis_bs = 'NC_10') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						" union all SELECT '"+rq+"' AS rq, '4#热水炉热水表' AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401108' and sb.ynsb_id = '402894b85f0e303a015f0f3840160110' and sis.ynsbsis_bs = 'NC_12') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m" +
						
						")",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery nyyhsjrbb5(DataQuery query ,String rq){
		DataQuery dbQuery = DataQuery
		.init(query,
				"(SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('蒸汽炉1#燃气' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4011840119' and sis.ynsbsis_bs = 'NC_18') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('蒸汽炉2#燃气' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('1' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4451fd011a' and sis.ynsbsis_bs = 'NC_F104_LJ') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('蒸汽炉蒸汽表' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('3' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f4785f6011f' and sis.ynsbsis_bs = 'NC_F101_LJ') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				" union all SELECT cast('"+rq+"' AS varchar(10)) AS rq, cast('蒸汽炉给水' AS varchar(20)) AS YNSB_GLBH, m.after AS LAST1VALUE, m.before AS LAST2VALUE, cast('10' AS varchar(10)) AS YNSB_NYZL, to_char(m.after - m.before) AS ljz, '' AS SHL, '' AS BYJSL, ynsb_fid FROM (SELECT WM_CONCAT(before) before, WM_CONCAT(after) after, ynsb_fid FROM (select t.rid, sum(decode(t.rid, '1', t.va, null)) AS before, sum(decode(t.rid, '2', t.va, null)) AS after, t.ynsb_fid FROM (SELECT rownum AS rid, jc.sisvalue AS va, sb.ynsb_fid FROM EAST_YNSB sb LEFT JOIN EAST_YNSBSIS sis on sis.ynsb_id = sb.ynsb_id LEFT JOIN ZD_TEST2 jc on jc.SISID = sis. ynsbsis_bs and jc.SISTIME in ('"+rq+" 00:00:00', '"+rq+" 23:59:00') WHERE sb.ynsb_fid = '3010401109' and sb.ynsb_id = '402894b85f0e303a015f0f46548b011e' and sis.ynsbsis_bs = 'NC_F102_LJ') t group by t.rid, t.ynsb_fid) group by ynsb_fid) m " +
				")",
				"RQ,YNSB_GLBH,LAST1VALUE,LAST2VALUE,YNSB_NYZL,LJZ,SHL,BYJSL,YNSB_FID");
		return dbQuery;
	}
	
	public DataQuery scjj(DataQuery query,String type){
		DataQuery dbQuery = new DataQuery();
		if("year".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.J200201 as J200201,a.J200202 as J200202,a.J200203 as J200203,a.J200204 as J200204,a.J200205 as J200205,a.J200206 as J200206,a.J200207 as J200207,a.J200208 as J200208,a.J200209 as J200209, b.JHZB_INDEX_STATE as STATE from J200 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"J200201,J200202,J200203,J200204,J200205,J200206,J200207,J200208,J200209,STATE").addUserWhere(" and 1=1 order by J200201 desc ,J200203");
		}else if("month".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.J201201 as J200201,a.J201202 as J200202,a.J201203 as J200203,a.J201204 as J200204,a.J201205 as J200205,a.J201206 as J200206,a.J201207 as J200207,a.J201208 as J200208,a.J201209 as J200209,b.JHZB_INDEX_STATE as STATE from J201 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"J200201,J200202,J200203,J200204,J200205,J200206,J200207,J200208,J200209,STATE").addUserWhere(" and 1=1 order by J200201 desc ,J200203");
		}
		return dbQuery;
	}
	
	public DataQuery sbjj(DataQuery query,String type){
		DataQuery dbQuery = new DataQuery();
		if("year".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.J202000 as J202000,a.J202200 as J202200,a.J202201 as J202201,a.J202202 as J202202,a.J202203 as J202203,a.J202204 as J202204,a.J202205 as J202205, b.JHZB_INDEX_STATE as STATE from J202 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"J202000,J202200,J202201,J202202,J202203,J202204,J202205,STATE").addUserWhere(" and 1=1 order by J202201 desc ,J202203");
		}else if("month".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.J203000 as J202000,a.J203200 as J202200,a.J203201 as J202201,a.J203202 as J202202,a.J203203 as J202203,a.J203204 as J202204,a.J203205 as J202205, b.JHZB_INDEX_STATE as STATE from J203 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"J202000,J202200,J202201,J202202,J202203,J202204,J202205,STATE").addUserWhere(" and 1=1 order by J202201 desc ,J202203");
		}
		return dbQuery;
	}
	
	public DataQuery zbtx(DataQuery query,String type){
		DataQuery dbQuery = new DataQuery();
		//能效指标
		if("nxzb".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.k200201 as RQ,a.k200202 as XMMC,a.k200203 as JGMC,a.k200204 as SBMC,a.k200205 as JLDW,a.k200206 as JHZB, b.JHZB_INDEX_STATE as STATE from k200 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"RQ,XMMC,JGMC,SBMC,JLDW,JHZB,STATE").addUserWhere(" and 1=1 order by RQ desc ,JGMC");
		} //质量指标
		else if("zlzb".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.k201201 as RQ,a.k201202 as XMMC,a.k201203 as JGMC,a.k201204 as SBMC,a.k201205 as JLDW,a.k201206 as JHZB, b.JHZB_INDEX_STATE as STATE from k201 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"RQ,XMMC,JGMC,SBMC,JLDW,JHZB,STATE").addUserWhere(" and 1=1 order by RQ desc ,JGMC");
		} //环保指标
		else if("hbzb".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.k202201 as RQ,a.k202202 as XMMC,a.k202203 as JGMC,a.k202204 as SBMC,a.k202205 as JLDW,a.k202206 as JHZB, b.JHZB_INDEX_STATE as STATE from k202 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"RQ,XMMC,JGMC,SBMC,JLDW,JHZB,STATE").addUserWhere(" and 1=1 order by RQ desc ,JGMC");
		} //设备指标
		else if("sbzb".equals(type)){
			dbQuery = DataQuery.init(query,
					"(select a.k203201 as RQ,a.k203202 as XMMC,a.k203203 as JGMC,a.k203204 as SBMC,a.k203205 as JLDW,a.k203206 as JHZB, b.JHZB_INDEX_STATE as STATE from k203 a  left join EAST_JHZB_INDEXSTATE b  on a.subid = b.jhzb_index_id ) ",
					"RQ,XMMC,JGMC,SBMC,JLDW,JHZB,STATE").addUserWhere(" and 1=1 order by RQ desc ,JGMC");
		}
		return dbQuery;
	}
	
}